services:
  gateway-application: #------------------------------------------------ gateway application
    build: ./gateway-application
    image: gateway-application
    container_name: gateway-application
    ports:
      - 18080:8080
    environment:
      GATEWAY_APPLICATION_URI: gateway-application:8080
      PATIENT_APPLICATION_URI: http://patient-application:8081
      FRONT_APPLICATION_URI: front-application:8082
    networks:
      - intra-network

  authentication-application: #------------------------------------------------ authentication application
    build: ./authentication-application
    image: authentication-application
    container_name: authentication-application
    restart: always
    ports:
      - 18085:8085
    environment:
      GATEWAY_APPLICATION_URI: gateway-application:8080
    volumes:
      - .m2:/root/.m2
    networks:
      - intra-network

  front-application: #-------------------------------------------------- front application
    build: ./front-application
    image: front-application
    container_name: front-application
    ports:
      - 18082:8082
    environment:
      GATEWAY_APPLICATION_URL: gateway-application:8080
    networks:
      - intra-network

  risk-application: #-------------------------------------------------- risk application
    build: ./risk-application
    image: risk-application
    container_name: risk-application
    ports:
      - 18084:8084
    environment:
      GATEWAY_APPLICATION_URI: gateway-application:8080
    networks:
      - intra-network

  patient-application: #------------------------------------------------ patient application
    build: ./patient-application
    image: patient-application
    container_name: patient-application
    depends_on:
      patient-database:
        condition: service_healthy
    ports:
      - 18081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://patient-database:3306/patients?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TestPassword
    networks:
      - intra-network

  patient-database: #------------------------------------------------------------- patient database (mysql)
    image: mysql:8.0.13
    container_name: patient-database
    environment:
      MYSQL_DATABASE: patients
      MYSQL_ROOT_PASSWORD: TestPassword
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -pTestPassword | grep alive || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    networks:
      - intra-network
    volumes:
      - patientDatabase:/var/lib/mysql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql

  note-application: #------------------------------------------------ note application
    build: ./note-application
    image: note-application
    container_name: note-application
    depends_on:
      patient-database:
        condition: service_healthy
    ports:
      - 18083:8083
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://note-database:27018/notes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TestPassword
    networks:
      - intra-network

  note-database: #--------------------------------------------------- note database
    image: mongo:6-jammy
    container_name: note-database
    command: mongod --port 27018
    ports:
      - 27018:27017
    networks:
      - intra-network
    volumes:
      - noteDatabase:/data/db
      - noteDatabaseConfig:/data/configdb

networks: #--------------------------------------------------------------- network & volume database
  intra-network:
    driver: bridge

volumes:
  patientDatabase:
  noteDatabase:
  noteDatabaseConfig: